name: CI

on: pull_request

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Prettier
        run: yarn && yarn format:check
