name: CI

on: pull_request

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "10.x"

      - name: Run Prettier
        run: yarn && yarn format:check
